name: CI

on:
  push:
    branches:
      - main  # или ветка, на которую вы хотите реагировать
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests with Allure
      run: |
        pytest --alluredir=allure-results

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Generate Allure Report
      run: |
        wget https://github.com/allure-framework/allure2/releases/download/2.13.8/allure-2.13.8.tgz
        tar -zxvf allure-2.13.8.tgz
        ./allure-2.13.8/bin/allure generate allure-results --clean -o allure-report

    - name: Upload Allure Report
      uses: actions/upload-artifact@v2
      with:
        name: allure-report
        path: allure-report

    - name: Update README with Allure results
      run: |
        echo "## Allure Test Report" > ALLURE_SUMMARY.md
        echo "![](allure-report/history/history-trend.png)" >> ALLURE_SUMMARY.md
        cat ALLURE_SUMMARY.md README.md > TEMP_README.md && mv TEMP_README.md README.md

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add README.md
        git commit -m "Update README with latest Allure test report"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
