name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests with Allure
      run: |
        pytest --alluredir=allure-results

    - name: List Allure results
      run: ls -R allure-results

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '22'

    - name: Generate Allure Report
      run: |
        wget https://github.com/allure-framework/allure2/releases/download/2.13.8/allure-2.13.8.tgz
        tar -zxvf allure-2.13.8.tgz
        ./allure-2.13.8/bin/allure generate allure-results --clean -o allure-report

    - name: List Allure report
      run: ls -R allure-report

    - name: Upload Allure Report
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report

    - name: Create or Update README with Allure results
      run: |
        echo "## Allure Test Report" > ALLURE_SUMMARY.md
        echo "![](allure-report/history/history-trend.png)" >> ALLURE_SUMMARY.md
        if [ ! -f README.md ]; then
          echo "# Project UI Autotests" > README.md
        fi
        cat ALLURE_SUMMARY.md README.md > TEMP_README.md && mv TEMP_README.md README.md

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add README.md
        git commit -m "Update README with latest Allure test report"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
