name: Publish report

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  publish-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download Allure Report artifact
        uses: actions/download-artifact@v4
        with:
          name: allure-report
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
